name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # আপনার মেইন ব্রাঞ্চের নাম যা-ই হোক (main বা master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          API_KEY: ${{ secrets.API_KEY }} # এখানে GitHub Secret থেকে Key নেওয়া হচ্ছে

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
